### ISSUE TITLE
Can not find the download counts for project which using wheels 

### ISSUE THREAD

**Issue by wincent8** [ofek/pypinfo#122]
hi, 
    I am try to find download counts for project https://github.com/intel/intel-extension-for-pytorch/, and in its readme, it said it can be install by pip with below command, 

`python -m pip install torch_ipex==1.9.0 -f https://software.intel.com/ipex-whl-stable`

but when i use the pypinfo torch_ipex, it shows the count as 0, 
anyone meet the similar issue? can anyone help me?
thanks,

**Comment by hugovk** [comment]
There's no `torch_ipex` project on _PyPI_:

* https://pypi.org/project/torch_ipex/

You're using pip's `-f` option, which tells pip to look at https://software.intel.com/ipex-whl-stable instead of PyPI, and we can see the files are indeed there.

So it's not downloaded from PyPI, the downloads stats aren't counted on PyPI and so pypinfo can't find any. You'd have to get in touch with Intel and ask them.

**Comment by wincent8** [comment]
thanks for the reply.
